controllers:
    resource: ../src/Controller/
    type: attribute



# # config/routes.yaml
# program_list:
#     path: /program/
#     # the controller value has the format 'controller_class::method_name'
#     controller: App\Controller\ProgramController::index

#     # config/routes.yaml
# app_index:
#     path: /
#     # the controller value has the format 'controller_class::method_name'
#     controller: App\Controller\DefaultController::index